//This is a placeholder object emulating an api response. The basic template is from the
//GitHub API.

export const GIT_PROFILES = [
    {
      "login": "GatorEcho",
      "id": 13266755,
      "node_id": "MDQ6VXNlcjEzMjY2NzU1",
      "avatar_url": "https://avatars3.githubusercontent.com/u/13266755?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/GatorEcho",
      "html_url": "https://github.com/GatorEcho",
      "followers_url": "https://api.github.com/users/GatorEcho/followers",
      "following_url": "https://api.github.com/users/GatorEcho/following{/other_user}",
      "gists_url": "https://api.github.com/users/GatorEcho/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/GatorEcho/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/GatorEcho/subscriptions",
      "organizations_url": "https://api.github.com/users/GatorEcho/orgs",
      "repos_url": "https://api.github.com/users/GatorEcho/repos",
      "events_url": "https://api.github.com/users/GatorEcho/events{/privacy}",
      "received_events_url": "https://api.github.com/users/GatorEcho/received_events",
      "type": "User",
      "site_admin": false,
      "name": "Marc Davenport",
      "company": null,
      "blog": "",
      "location": null,
      "email": null,
      "hireable": null,
      "bio": null,
      "public_repos": 5,
      "public_gists": 0,
      "followers": 6,
      "following": 5,
      "created_at": "2015-07-10T03:05:01Z",
      "updated_at": "2018-06-06T13:05:10Z",
      "languages": ['js', 'react', 'node-js'],
      "quote": "Lorem ipsum dolor sit amet."
  },
  {
    "login": "ellablac",
    "id": 12832281,
    "node_id": "MDQ6VXNlcjEyODMyMjgx",
    "avatar_url": "https://avatars2.githubusercontent.com/u/12832281?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/ellablac",
    "html_url": "https://github.com/ellablac",
    "followers_url": "https://api.github.com/users/ellablac/followers",
    "following_url": "https://api.github.com/users/ellablac/following{/other_user}",
    "gists_url": "https://api.github.com/users/ellablac/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/ellablac/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/ellablac/subscriptions",
    "organizations_url": "https://api.github.com/users/ellablac/orgs",
    "repos_url": "https://api.github.com/users/ellablac/repos",
    "events_url": "https://api.github.com/users/ellablac/events{/privacy}",
    "received_events_url": "https://api.github.com/users/ellablac/received_events",
    "type": "User",
    "site_admin": false,
    "name": null,
    "company": null,
    "blog": "",
    "location": "St. Louis, MO area",
    "email": null,
    "hireable": null,
    "bio": null,
    "public_repos": 2,
    "public_gists": 1,
    "followers": 4,
    "following": 6,
    "created_at": "2015-06-10T15:33:26Z",
    "updated_at": "2018-05-08T05:00:16Z",
    "languages": ['js', 'react', 'node-js'],
    "quote": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."
  },
  {
    "login": "michael-lang",
    "id": 326012,
    "node_id": "MDQ6VXNlcjMyNjAxMg==",
    "avatar_url": "https://avatars0.githubusercontent.com/u/326012?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/michael-lang",
    "html_url": "https://github.com/michael-lang",
    "followers_url": "https://api.github.com/users/michael-lang/followers",
    "following_url": "https://api.github.com/users/michael-lang/following{/other_user}",
    "gists_url": "https://api.github.com/users/michael-lang/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/michael-lang/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/michael-lang/subscriptions",
    "organizations_url": "https://api.github.com/users/michael-lang/orgs",
    "repos_url": "https://api.github.com/users/michael-lang/repos",
    "events_url": "https://api.github.com/users/michael-lang/events{/privacy}",
    "received_events_url": "https://api.github.com/users/michael-lang/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Michael Lang",
    "company": null,
    "blog": "http://www.nexul.com/",
    "location": "Saint Louis, MO, USA",
    "email": null,
    "hireable": null,
    "bio": null,
    "public_repos": 12,
    "public_gists": 0,
    "followers": 8,
    "following": 5,
    "created_at": "2010-07-08T03:33:13Z",
    "updated_at": "2018-03-05T23:49:18Z",
    "languages": ['js', 'angular', 'vuejs', 'react', 'node-js'],
    "quote": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."
  },
  {
    "login": "thesolidmoose",
    "id": 26205610,
    "node_id": "MDQ6VXNlcjI2MjA1NjEw",
    "avatar_url": "https://avatars2.githubusercontent.com/u/26205610?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/thesolidmoose",
    "html_url": "https://github.com/thesolidmoose",
    "followers_url": "https://api.github.com/users/thesolidmoose/followers",
    "following_url": "https://api.github.com/users/thesolidmoose/following{/other_user}",
    "gists_url": "https://api.github.com/users/thesolidmoose/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/thesolidmoose/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/thesolidmoose/subscriptions",
    "organizations_url": "https://api.github.com/users/thesolidmoose/orgs",
    "repos_url": "https://api.github.com/users/thesolidmoose/repos",
    "events_url": "https://api.github.com/users/thesolidmoose/events{/privacy}",
    "received_events_url": "https://api.github.com/users/thesolidmoose/received_events",
    "type": "User",
    "site_admin": false,
    "name": null,
    "company": null,
    "blog": "",
    "location": null,
    "email": null,
    "hireable": true,
    "bio": null,
    "public_repos": 4,
    "public_gists": 0,
    "followers": 7,
    "following": 9,
    "created_at": "2017-03-05T18:45:14Z",
    "updated_at": "2018-05-24T17:15:09Z",
    "languages": ['js', 'python'],
    "quote": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."
  },
  {
    "login": "Samibanley",
    "id": 25395859,
    "node_id": "MDQ6VXNlcjI1Mzk1ODU5",
    "avatar_url": "https://avatars0.githubusercontent.com/u/25395859?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Samibanley",
    "html_url": "https://github.com/Samibanley",
    "followers_url": "https://api.github.com/users/Samibanley/followers",
    "following_url": "https://api.github.com/users/Samibanley/following{/other_user}",
    "gists_url": "https://api.github.com/users/Samibanley/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Samibanley/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Samibanley/subscriptions",
    "organizations_url": "https://api.github.com/users/Samibanley/orgs",
    "repos_url": "https://api.github.com/users/Samibanley/repos",
    "events_url": "https://api.github.com/users/Samibanley/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Samibanley/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Samantha Bley",
    "company": null,
    "blog": "",
    "location": "St. Louis, MO",
    "email": null,
    "hireable": null,
    "bio": null,
    "public_repos": 3,
    "public_gists": 0,
    "followers": 3,
    "following": 4,
    "created_at": "2017-01-27T23:24:32Z",
    "updated_at": "2018-05-09T04:58:10Z",
    "languages": ['js', 'react', 'node-js'],
    "quote": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."
  },
  {
    "login": "jbburf",
    "id": 6198892,
    "node_id": "MDQ6VXNlcjYxOTg4OTI=",
    "avatar_url": "https://avatars3.githubusercontent.com/u/6198892?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/jbburf",
    "html_url": "https://github.com/jbburf",
    "followers_url": "https://api.github.com/users/jbburf/followers",
    "following_url": "https://api.github.com/users/jbburf/following{/other_user}",
    "gists_url": "https://api.github.com/users/jbburf/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/jbburf/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/jbburf/subscriptions",
    "organizations_url": "https://api.github.com/users/jbburf/orgs",
    "repos_url": "https://api.github.com/users/jbburf/repos",
    "events_url": "https://api.github.com/users/jbburf/events{/privacy}",
    "received_events_url": "https://api.github.com/users/jbburf/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Ben Burford",
    "company": null,
    "blog": "",
    "location": "St. Louis, MO - USA",
    "email": null,
    "hireable": null,
    "bio": null,
    "public_repos": 3,
    "public_gists": 0,
    "followers": 6,
    "following": 4,
    "created_at": "2013-12-16T16:56:32Z",
    "updated_at": "2018-05-11T16:16:40Z",
    "languages": ['js', 'react', 'python'],
    "quote": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."
  },
  {
    "login": "vivianmaxine",
    "id": 19582376,
    "node_id": "MDQ6VXNlcjE5NTgyMzc2",
    "avatar_url": "https://avatars2.githubusercontent.com/u/19582376?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/vivianmaxine",
    "html_url": "https://github.com/vivianmaxine",
    "followers_url": "https://api.github.com/users/vivianmaxine/followers",
    "following_url": "https://api.github.com/users/vivianmaxine/following{/other_user}",
    "gists_url": "https://api.github.com/users/vivianmaxine/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/vivianmaxine/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/vivianmaxine/subscriptions",
    "organizations_url": "https://api.github.com/users/vivianmaxine/orgs",
    "repos_url": "https://api.github.com/users/vivianmaxine/repos",
    "events_url": "https://api.github.com/users/vivianmaxine/events{/privacy}",
    "received_events_url": "https://api.github.com/users/vivianmaxine/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Vivian",
    "company": null,
    "blog": "",
    "location": "St. Louis, MO",
    "email": null,
    "hireable": null,
    "bio": "Career changer:\r\nEd --> WebDev",
    "public_repos": 2,
    "public_gists": 0,
    "followers": 3,
    "following": 1,
    "created_at": "2016-05-26T02:36:00Z",
    "updated_at": "2018-05-26T00:26:29Z",
    "languages": ['js', 'react', 'node-js'],
    "quote": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."
  }
]